name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run:  go get -v "./..."
      working-directory: "."

    - name: Build agent cli
      run: go build -v -o /tmp/dnspot-linux-amd64.bin .
      working-directory: "./cmd/agent"
      env:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

    - name: Build linux x64
      run: go build -v -o /tmp/dnspot-linux-amd64.bin .
      working-directory: "./cmd/server"
      env:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

    - name: Build linux x64
      run: go build -v -o /tmp/dnspot-linux-amd64.bin .
      working-directory: "./tui"
      env:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

