name: Build Test

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run:  go get -v 
      working-directory: "."

    - name: Build linux x64
      run: go build -v -o /tmp/dnspot-linux-amd64.bin .
      working-directory: "./"
      env:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

    - name: Upload Linux binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/dnspot-linux-amd64.bin
        asset_name: dnspot-linux-amd64.bin
        tag: ${{ github.ref }}
        overwrite: true
        body: ""